// ng/airulus/layouts/src/lib/view/view.component.ts
import {
  Component,
  Input,
  OnInit
  } from '@angular/core';

@Component({
  selector: 'adk-view',
  templateUrl: 'view.component.html',
  styleUrls: ['view.component.scss']
})
export class ViewComponent {

  @Input()
  public contentVerticalPosition?: 'top' | 'centered' | 'bottom';

  @Input()
  public contentHorizontalPosition?: 'left' | 'centered' | 'right';
}

<div 
  class="view"
  [class.horizontal-centered]="contentHorizontalPosition === 'centered'"
  [class.horizontal-right]="contentHorizontalPosition === 'right'"
  [class.vertical-centered]="contentVerticalPosition === 'centered'"
  [class.vertical-bottom]="contentVerticalPosition === 'bottom'"
>
  <ng-content></ng-content>
</div>

// react/airulus/layout/src/lib/components/templates/view/view.component.tsx
import * as React from 'react';
import { classnames } from '@adk/airulus/cdk';
const styles = require('./view.component.scss');

export interface ViewProps extends React.HTMLAttributes<HTMLDivElement> {
  as?: keyof React.ReactHTML;
  contentVerticalPosition?: 'top' | 'centered' | 'bottom';
  contentHorizontalPosition?: 'left' | 'centered' | 'right';
  ref?: any;
}

export type ViewComponent = React.FC<ViewProps>

/**
 *
 */
export const View: ViewComponent = React.memo(
  React.forwardRef<HTMLDivElement, ViewProps>(({ 
    children, 
    as, 
    className, 
    contentVerticalPosition,
    contentHorizontalPosition,
    ...props 
  }, ref) => {
    const elementClassNames = classnames(className, styles.view, {
      [styles.horizontalCentered]: contentHorizontalPosition === 'centered',
      [styles.horizontalRight]: contentHorizontalPosition === 'right',
      [styles.verticalCentered]: contentVerticalPosition === 'centered',
      [styles.verticalBottom]: contentVerticalPosition === 'bottom',
    });
    const HtmlTag: any = as;
    return (
      <HtmlTag 
        ref={ref} 
        className={elementClassNames} 
        {...props}
      >{children}</HtmlTag>
    );
  }));

View.displayName = 'View';

View.defaultProps = {
  as: 'div',
  contentHorizontalPosition: 'left',
  contentVerticalPosition: 'top'
};
